config/routes.rb
Rails.application.routes.draw do
 

  resources :messages
  resources :conversations
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'} ,:controllers => { registrations: "registrations", sessions: 'sessions' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as:  :register
    get 'login', to: 'devise/sessions#new', as:  :login
    get 'logout', to: 'devise/sessions#destroy', as:  :logout , method: :delete
    get 'settings', to: 'devise/registrations#edit', as:  :settings   
  end
  authenticated :user do
    root to: 'posts#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#index'
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :dreams
  

  resources :chats
  resources :users
  resources :learns
  resources :activities
  resources :sounds
  resources :creates
  resources :videos
  resources :galleries
   get 'learn/index'
   get 'pages/terms'
   get 'pages/about'
    get 'pages/contact'
 resources :pages
  resources 'home'
  resources :learn
  resources :post do
    member do
        put "like", to: "posts#upvote"
        put "dislike", to: "posts#downvote"
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :posts do  
   resources :comments
  end  
  resources :comments do  
   resources :replies
  end  
  resources :followings
  resources :follows
  resources :people
  resources :profile
  resources :update
  resources :feed
  resources :user_networks do
    member do
      put :block
    end
  end


/ this should be in the down /
  get ':username', to: 'profile#show', as: :username
  get ':username/biography' , to: 'biography#index', as: :biography
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user}

  belongs_to :user
  belongs_to :post
  has_many :replies, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id

	  if @comment.save
	    flash[:success] = "You commented the hell out of that post!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end

	def destroy
	  @comment = @post.comments.find(params[:id])
	  @comment.destroy
	  flash[:success] = "Comment deleted :("
	  redirect_to root_path
	end

	private

	def comment_params
	  params.require(:comment).permit(:content)
	end

	def set_post
	  @post = Post.find(params[:post_id])
	end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
_<%= @posts.each do |post| %>
<div class="ui comments segment" style="text-align:left; display:none"  id="post_<%= post.id%>">
		<% if post.comments.present? %>
 
  			<h3 class="ui dividing header">Comments</h3>
  	  <% post.comments.each do |comment| %>	 
			  <div class="comment">
			  <%= link_to comment.user.username.capitalize, class: "header" do %>
					  <a class="avatar">
				    	   <%= image_tag comment.user.avatar.url(:thumb), class: "ui avatar " %>
						</a>
   		 <div class="content">
      			<a class="author"><%= comment.user.firstname.capitalize %></a><% end %>
			      <div class="metadata">
			        <span class="date">
			        <%= " #{time_ago_in_words(comment.created_at)} ago" %></span>
			      </div>
      			<div class="text">
       					<%= comment.content%> 
							<% if comment.user == current_user  %>
								<%=  link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
									<i class="icon trash"></i> 
								<% end %>
							<% end %>
     			 </div>
			      <div class="actions">
			        <a class="reply">Reply</a>
			      </div>
		 </div>
	     <div class="comments">
			    <% comment.replies.each do |reply| %>			    
			      <div class="comment">
			    <%= link_to reply.user.username.capitalize, class: "header" do %>
							<a class="avatar">
					       		<%= image_tag reply.user.avatar.url(:thumb), class: "ui avatar " %>
							</a>
			<div class="content">
			          <a class="author"><%= reply.user.firstname.capitalize %></a>
			    <% end %>

			          <div class="metadata">
			            <span class="date"> 
			            	<%="#{time_ago_in_words(reply.created_at)} ago" %></span>
			          	</div>
			          <div class="text">
			             	<%= reply.content%> 
				      		<% if reply.user == current_user  %>
								<%=  link_to comment_reply_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
										<i class="icon trash"></i> 
						        <% end %>
				            <% end %>
			          </div>
			  
			 </div>
		</div>
			      <% end %>


			    </div>

			     <div class='ui form'>
			   
			   <%= form_for [comment, comment.replies.new] do |f| %>
            			
            			<h5><%= f.text_field :content, placeholder: 'Reply', style: 'margin-top:-30px;' %></h5>
            	<% end %>
            	</div>
			
			  </div>
			  <% end %>
			   <% end %>
  		</div>
<% end %>