config/routes.rb
Rails.application.routes.draw do
 

  resources :messages
  resources :conversations
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'} ,:controllers => { registrations: "registrations", sessions: 'sessions' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as:  :register
    get 'login', to: 'devise/sessions#new', as:  :login
    get 'logout', to: 'devise/sessions#destroy', as:  :logout , method: :delete
    get 'settings', to: 'devise/registrations#edit', as:  :settings   
  end
  authenticated :user do
    root to: 'posts#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#index'
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :dreams
  

  resources :chats
  resources :users
  resources :learns
  resources :activities
  resources :sounds
  resources :creates
  resources :videos
  resources :galleries
   get 'learn/index'
   get 'pages/terms'
   get 'pages/about'
    get 'pages/contact'
 resources :pages
  resources 'home'
  resources :learn
  resources :post do
    member do
        put "like", to: "posts#upvote"
        put "dislike", to: "posts#downvote"
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :posts do  
   resources :comments
  end  
  resources :comments do  
   resources :replies
  end  
  resources :followings
  resources :follows
  resources :people
  resources :profile
  resources :update
  resources :feed
  resources :user_networks do
    member do
      put :block
    end
  end


/ this should be in the down /
  get ':username', to: 'profile#show', as: :username
  get ':username/biography' , to: 'biography#index', as: :biography
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end	
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_filter :authenticate_user!

  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div id="chat-window" style="width:280px; hieght:250px;">
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.username %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='minus icon'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='close icon'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
</div>

<%= subscribe_to conversation_path(@conversation) %>