config/routes.rb
Rails.application.routes.draw do
 

  resources :messages
  resources :conversations
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'} ,:controllers => { registrations: "registrations", sessions: 'sessions' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as:  :register
    get 'login', to: 'devise/sessions#new', as:  :login
    get 'logout', to: 'devise/sessions#destroy', as:  :logout , method: :delete
    get 'settings', to: 'devise/registrations#edit', as:  :settings   
  end
  authenticated :user do
    root to: 'posts#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#index'
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :dreams
  

  resources :chats
  resources :users
  resources :learns
  resources :activities
  resources :sounds
  resources :creates
  resources :videos
  resources :galleries
   get 'learn/index'
   get 'pages/terms'
   get 'pages/about'
    get 'pages/contact'
 resources :pages
  resources 'home'
  resources :learn
  resources :post do
    member do
        put "like", to: "posts#upvote"
        put "dislike", to: "posts#downvote"
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :posts do  
   resources :comments
  end  
  resources :comments do  
   resources :replies
  end  
  resources :followings
  resources :follows
  resources :people
  resources :profile
  resources :update
  resources :feed
  resources :user_networks do
    member do
      put :block
    end
  end


/ this should be in the down /
  get ':username', to: 'profile#show', as: :username
  get ':username/biography' , to: 'biography#index', as: :biography
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if user_signed_in?
  		redirect_to posts_path
  	else
  	   render :layout => false
  	end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuvi Tuvi</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
 	 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 	 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 	 <%= csrf_meta_tags %>
</head>
<body sytle="overflow:hidden; " class="container-violet">

<div class="" style="margin-bottom:-0px;">
<div class="ui middle aligned centered bg" style="text-align:center;"><%= image_tag "white_logo.svg", class: "ui medium  image centered"  %> 
</div>
<div style="" class="bg login_home">			  
				

				    <div class="ui form">
				    <div class=" fields">
				    <div class="two wide computer field"></div>
				      <div class=" three wide tablet five wide computer field">
				  <%= form_for(:user, class: 'ui form', :url => session_path(:user)) do |f| %>
						        <div class="ui left icon input">
				          <%= f.text_field :login, placeholder: 'Email Or Username' %>
				          <i class="user icon"></i>
				        </div>
				        <br><br>
				        	<div class="ui checkbox"><%= f.check_box :remember_me %><%= f.label :remember_me ,'Remember me', class: "whited" %></div>
				    			
				    	
				      </div>
				      <div class="five wide field">
				        
				        <div class="ui left icon input">
				          <%= f.password_field :password, placeholder: 'Password' %>
				          <i class="lock icon"></i>
				        
				        </div>
				          	<br><br>	<%= link_to "Forgot your password?", new_password_path(:user), class: "whited" %>
				        </div>
				        <div class="two wide field center aligned" style="text-align:center;">
				        
				   
				      <%= f.submit 'Sign in', class: 'ui violet submit button' %>  
				      
				      </div>
				     
				      </div>
				      	<div class="ten widefield">
				    			
				      </div>  
						  		
						  		<% end %>
				    </div>
</div>
<div class="ui stackable grid">
<div class="ui sixteen wide tablet three wide computer column "  >
<div class='ui basic segment' sytle="margin-top:70%; height:100%; " >	
<span class="ui whited" >Stay connected<br> Get the tuvituvi app now.  <br><br><br> <button class="ui login button violet">Get it now</button>
<button class="ui logged button inverted ">Get it now</button></span>
</div>
</div>
<div class="ui sixteen wide tablet ten wide computer column middle aligned">
</div>
<div class="ui three wide computer-only column ">
	<div class="ui middle aligned" ><span class="ui centered whited"> Dont have an account?<br> Sign up now.  Its free.<br><br><br></span></div>
<button class="ui login button inverted ">Sign up</button>
<%= link_to new_user_registration_path  do %><button class="ui logged button inverted" >Sign-up</button> <% end %></div>

</div>
</div>
	

	<div class="ui modal">
	<i class="close icon"></i>
	<div class="content">
	<div class="header center aligned"> <h2 style="text-align:center;">Feeling Left Out? - Sign Up</h2> </div><br>
		<div class="ui  grid middle aligned">
				<div class="eight wide column">
		  			

  					<div class="ui form">
  	
				      <div class="field">
 		     			<%= form_for(User.new, :as => :user,  :url => registration_path(:user) ,:html => {:multipart => true}) do |f| %>
		     				
		                        <div class="ui left icon input">
									<%= f.text_field :username, placeholder: 'Username (only letters and numbers)' %>
									<i class="user icon"></i>
								</div>
						</div>
		                 <div class="field">  
		                        <div class="ui left icon input">
									 <%= f.email_field :email,placeholder: 'Email' %>
									 <i class="mail icon"></i>
								</div>
						</div>
		                 <div class="field">  
		                        <div class="ui left icon input">
									 <%= f.password_field :password, placeholder: 'Password' %>
									 <i class="lock icon"></i>
								</div>
						</div>
		             <div class="field" style="text-align:center">
		                       <%= f.submit "Sign up now", class: 'ui button primary center aligned' , :id => 'left' %>
		                <%end%> 
		                </div>
		           	</div>
					</div>
					<div class="eight wide column ">
					<%= image_tag 'logo.svg' %>
					</div>
  		</div>
	</div>
</div>				
	
	</div> 	 	
	

</div>
<script type="text/javascript">
$(document).on("click", ".login", function () {
    $(".ui.modal").modal()
    .modal("show");
});
$('.ui.checkbox')
  .checkbox()
;
$('.ui.dropdown')
  .dropdown()
;

$(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});
</script>
</body>
</html>